name: Github CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11  # or your desired Python version
          activate-environment: myenv
          environment-file: environments/environment.yaml

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Week 
        run: |
          cd week6
          sudo apt install fastqc
          jupyter nbconvert --to html --execute week6.ipynb --output summary.html
 
      - name: Upload notebook summary
        uses: actions/upload-artifact@v4
        with:
          name: notebook-summary
          path: week5/summary.html
          
      - name: Add notebook HTML to job summary
        run: |
          echo "<h2>Week 6 Notebook Summary</h2>" >> $GITHUB_STEP_SUMMARY
          echo "<iframe src='week5/summary.html' width='100%' height='800'></iframe>" >> $GITHUB_STEP_SUMMARY

